features:
  autoMessage: true
  autoRestart: true
  commands: true
  entityCount: true
  newbie: true
  opCommand: true
  portalWarpNpc: true
  resetWorld: true
  safetyLogin: true
  suppressAdvancementsOp: true
  vanilandCommand: true
  vote: true
  worldWarpMobNpc: true
  worldWarpNpc: true
