name: VanilandPlugin
version: '${version}'
main: land.vani.plugin.main.VanilandPlugin
api-version: 1.17
authors: [ rona_tombo ]
depend:
  - EasySpigotAPI
  - WorldGuard
  - LuckPerms
  - LunaChat
  - BanManager
  - Votifier
  - MultiverseCore

permissions:
  vaniland.admin.mcbans:
    default: op
    description: Can show MCBans lookup information
  vaniland.admin.inspector:
    default: op
    description: Can enable/disable inspector mode
  vaniland.admin.tp.world:
    default: op
    description: Open world teleport menu
