name: VanilandPlugin
version: '${version}'
main: land.vani.plugin.VanilandPlugin
api-version: 1.17
authors: [ rona_tombo ]
depend:
  - EasySpigotAPI

permissions:
  vaniland.admin.mcbans:
    default: op
    description: Can show MCBans lookup information
  vaniland.admin.inspector:
    default: op
    description: Can enable/disable inspector mode
