name: VanilandPlugin
version: '${version}'
main: land.vani.plugin.core.VanilandPlugin
api-version: 1.19
authors: [ rona_tombo ]
load: POSTWORLD
softdepend:
  - Citizens
  - Multiverse-Core
  - WorldGuard
  - LuckPerms
  - LunaChat
  - BanManager
  - Votifier
