name: VanilandPlugin
version: '${version}'
main: land.vani.plugin.core.VanilandPlugin
api-version: 1.17
authors: [ rona_tombo ]
load: STARTUP
loadbefore:
  - WorldGuard
  - LuckPerms
  - LunaChat
  - BanManager
  - Votifier
  - Multiverse-Core
