name: detekt
on:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle/wrapper/gradle-wrapper.properties') }}
            ${{ runner.os }}-gradle-
      - name: Run detekt
        run: ./gradlew detekt
      - name: Setup reviewdog
        if: always()
        uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        if: always()
        run: cat build/reports/detekt/main.xml | reviewdog -level=warning -f=checkstyle -name=detekt -reporter=github-pr-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload results to GitHub repository
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/build/reports/detekt/main.sarif
          checkout_path: ${{ github.workspace }}
